### PR TITLE
Alex demo preparations

### PR DESCRIPTION
**Pull request by XOR-SABER**
Done for demo approve in the morning

### CODE REVIEW

**Comment by XOR-SABER** [comment]
Done, am getting ready for class.

**Review by Af0n — APPROVED** [review]
dayum did you sleep? good work

**Comment by XOR-SABER** [comment]
Sleep is for weaklings.

**Comment by XOR-SABER** [comment]
Mr _Incredible11-1

**Review by EdwardLe0n — APPROVED** [review]
Looks good, pls comment your code a bit more moving forward

**Pull request merged**
